[package]
name = "module-evm-utility-macro"
version = "2.26.0"
authors = ["Acala Developers"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = { workspace = true }
syn = { workspace = true, features = ["full", "fold", "extra-traits", "visit"] }
proc-macro2 = { workspace = true }
module-evm-utility = { workspace = true, features = ["std"] }
