[package]
name = "module-evm-utility-macro"
version = "2.21.0"
authors = ["Acala Developers"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.20"
syn = { version = "1.0.98", features = ["full", "fold", "extra-traits", "visit"] }
proc-macro2 = "1.0.40"
module-evm-utility = { path = ".." }
