[package]
name = "acala-dev"
version = "0.7.11"
authors = ["Acala Developers"]
edition = "2018"

[[bin]]
name = "acala-dev"
path = "src/main.rs"

[dependencies]
futures = "0.3.4"
parity-util-mem = { version = "0.9.0", default-features = false, features = ["jemalloc-global"] }
acala-dev-cli = { path = "cli" }
acala-dev-service = { path = "service" }

[features]
runtime-benchmarks = [
	"acala-dev-cli/runtime-benchmarks",
]
with-ethereum-compatibility = [
	"acala-dev-service/with-ethereum-compatibility"
]
with-mandala-runtime = []
