[package]
name = "module-vaults"
version = "0.0.1"
authors = ["Acala Developers"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
system = { package = "frame-system", git = "https://github.com/paritytech/substrate.git", default-features = false }
frame-support = { package = "frame-support", git = "https://github.com/paritytech/substrate.git", default-features = false }
rstd = { package = "sp-std", git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", default-features = false }
orml-traits = { package = "orml-traits", path = "../../orml/traits", default-features = false }
primitives = { package = "module-primitives", path = "../primitives", default-features = false }
support = { package = "module-support", path = "../support", default-features = false }
orml-tokens = { package = "orml-tokens", path = "../../orml/tokens", default-features = false }

[dev-dependencies]
su-primitives = { package = "sp-core",  git = "https://github.com/paritytech/substrate.git", default-features = false }
runtime-io = { package = "sp-io", git = "https://github.com/paritytech/substrate.git", default-features = false }
debits = { package = "module-debits", path = "../debits", default-features = false }
pallet-balances= { package = "pallet-balances", git = "https://github.com/paritytech/substrate.git", default-features = false }
orml-currencies = { package = "orml-currencies", path = "../../orml/currencies", default-features = false }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"system/std",
	"frame-support/std",
	"rstd/std",
	"sp-runtime/std",
	"orml-traits/std",
	"primitives/std",
	"support/std",
	"orml-tokens/std",
]
