[package]
name = "module-cdp-engine-benchmarking"
version = "0.6.2"
authors = ["Acala Developers"]
edition = "2018"

[dependencies]
sp-runtime = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }
frame-support = { version = "2.0.0", default-features = false }
frame-system = { version = "2.0.0", default-features = false }
frame-benchmarking = { version = "2.0.0", default-features = false }
orml-oracle = { path = "../../../orml/oracle", default-features = false }
orml-traits = { path = "../../../orml/traits", default-features = false }
prices = { package = "module-prices", path = "../../prices", default-features = false }
primitives = { package = "acala-primitives", path = "../../../primitives", default-features = false }
support = { package = "module-support", path = "../../support", default-features = false }
cdp-engine = { package = "module-cdp-engine", path = "../../cdp_engine", default-features = false }
loans = { package = "module-loans", path = "../../loans", default-features = false }
dex = { package = "module-dex", path = "../../dex", default-features = false }
emergency_shutdown = { package = "module-emergency-shutdown", path = "../../emergency_shutdown", default-features = false }

[dev-dependencies]
serde = { version = "1.0.101" }
codec = { package = "parity-scale-codec", version = "1.3.0", features = ["derive"] }
sp-core = { version = "2.0.0", default-features = false }
sp-io = { version = "2.0.0", default-features = false }
pallet-balances = { version = "2.0.0", default-features = false }
orml-currencies = { path = "../../../orml/currencies", default-features = false }
orml-tokens = { path = "../../../orml/tokens", default-features = false }
cdp-treasury = { package = "module-cdp-treasury", path = "../../cdp_treasury", default-features = false }
pallet-timestamp = { version = "2.0.0" }

[features]
default = ["std"]
std = [
	"sp-runtime/std",
	"sp-std/std",
	"frame-support/std",
	"frame-system/std",
	"frame-benchmarking/std",
	"cdp-engine/std",
	"loans/std",
	"support/std",
	"orml-oracle/std",
	"orml-traits/std",
	"prices/std",
	"dex/std",
	"emergency_shutdown/std",
]
