[package]
name = "e2e-tests"
version = "2.2.1"
authors = ["Acala Developers"]
edition = "2021"

[dependencies]
#log = "0.4.14"
#hex-literal = "0.3.1"
#cumulus-primitives-parachain-inherent = { git = "https://github.com/paritytech/cumulus", branch = "master" }
#frame-system = { git = "https://github.com/paritytech/substrate", branch = "master" }
#frame-support = { git = "https://github.com/paritytech/substrate", branch = "master" }
#frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "master" }
#pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "master" }
#pallet-sudo = { git = "https://github.com/paritytech/substrate", branch = "master" }
#
#sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "master" }
#sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "master" }
#sp-consensus-babe= { git = "https://github.com/paritytech/substrate", branch = "master" }
#sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "master" }
#sc-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "master" }
#sc-consensus-babe= { git = "https://github.com/paritytech/substrate", branch = "master" }
#sc-consensus-manual-seal = { git = "https://github.com/paritytech/substrate", branch = "master" }
#sc-service = { git = "https://github.com/paritytech/substrate", branch = "master" }
#sc-executor = { git = "https://github.com/paritytech/substrate", branch = "master" }
#sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "master" }
#sc-network = { git = "https://github.com/paritytech/substrate", branch = "master" }
#sc-network-test = { git = "https://github.com/paritytech/substrate", branch = "master" }
#sc-informant = { git = "https://github.com/paritytech/substrate", branch = "master" }
#sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "master" }
#
#sp-core = { git = "https://github.com/paritytech/substrate", branch = "master" }
#sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "master" }
#sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "master" }
#sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "master" }
#sp-api = { git = "https://github.com/paritytech/substrate", branch = "master" }
#sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "master" }
#sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "master" }

test-service = { path = "./test-service" }

#module-evm = { path = "../../modules/evm" }
#module-transaction-payment = { path = "../../modules/transaction-payment" }
#module-emergency-shutdown = { path = "../../modules/emergency-shutdown" }
#module-cdp-engine = { path = "../../modules/cdp-engine" }
#ecosystem-renvm-bridge = { path = "../../ecosystem-modules/ren/renvm-bridge" }
#node-runtime = { package = "mandala-runtime", path = "../../runtime/mandala" }
#node-primitives = { package = "acala-primitives", path = "../../primitives" }
#node-cli = { package = "acala-cli", path = "../cli", features = ["with-mandala-runtime"] }
#node-service = { package = "acala-service", path = "../service", features = ["with-mandala-runtime"] }
#runtime-common = { path = "../../runtime/common" }
