[package]
name = "module-dex-rpc"
version = "0.4.4"
authors = ["Acala Developers"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "1.3.0" }
jsonrpc-core = "14.0.5"
jsonrpc-core-client = "14.0.5"
jsonrpc-derive = "14.0.5"
sp-runtime = { version = "2.0.0-rc1" }
sp-api = { version = "2.0.0-rc1" }
sp-blockchain = { version = "2.0.0-rc1" }
module-dex-rpc-runtime-api = { path = "runtime-api" }
