[package]
name = "acala-cli"
version = "0.8.0"
authors = ["Acala Developers"]
edition = "2018"

[dependencies]
log = "0.4.8"
structopt = "0.3.8"
codec = { package = "parity-scale-codec", version = "2.0.0" }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }

cumulus-client-service = { git = "https://github.com/paritytech/cumulus", branch = "rococo-v1" }
cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus", branch = "rococo-v1" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1" }
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1" }
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1" }

inspect = { package = "acala-inspect", path = "../../../inspect" }
service = { package = "acala-service", path = "../service", default-features = false, optional = true }

[build-dependencies]
orml-build-script-utils = { path = "../../../orml/build-script-utils"}

[features]
default = [ "wasmtime", "cli", "with-mandala-runtime" ]
wasmtime = [ "sc-cli/wasmtime" ]
cli = [
	"service",
	"sp-core",
	"sc-cli",
	"sc-service",
	"frame-benchmarking-cli",
]
runtime-benchmarks = [ "service/runtime-benchmarks" ]
with-mandala-runtime = [
	"service/with-mandala-runtime",
]
with-karura-runtime = [
	"service/with-karura-runtime",
]
with-acala-runtime = [
	"service/with-acala-runtime",
]
with-all-runtime = [
	"service/with-all-runtime",
]
