name: Verify bootnotes

on:
  schedule:
    - cron: "00 04 * * 1" # 4AM weekly on monday

jobs:
  verify-karura:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: verify bootnotes
        run: |
          ./scripts/verify-bootnodes.sh karura
  verify-acala:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: verify bootnotes
        run: |
          ./scripts/verify-bootnodes.sh acala
